//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMDynamicPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMDynamicPackage()
        {
            this.DynamicAppCustomers = new HashSet<DynamicAppCustomer>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public string Index { get; set; }
        public string PackageID { get; set; }
        public string PackageName { get; set; }
        public string PackageVersion { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> SourceDate { get; set; }
        public Nullable<System.DateTime> LastRefresh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicAppCustomer> DynamicAppCustomers { get; set; }
    }
}
