//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMOperatingSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMOperatingSystem()
        {
            this.DynamicAppCustomers = new HashSet<DynamicAppCustomer>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public string Name { get; set; }
        public string PackageId { get; set; }
        public string PkgSourcePath { get; set; }
        public Nullable<int> SourceSize { get; set; }
        public Nullable<int> SourceVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicAppCustomer> DynamicAppCustomers { get; set; }
    }
}
