//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.DynamicAppCustomers = new HashSet<DynamicAppCustomer>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public string CollectionID { get; set; }
        public string Domain { get; set; }
        public string DomainShort { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string OU { get; set; }
        public string RDSVersion { get; set; }
        public string SCOM { get; set; }
        public string System { get; set; }
        public string XAController { get; set; }
        public string OfficeVersion { get; set; }
        public string XenAppFarmName { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicAppCustomer> DynamicAppCustomers { get; set; }
    }
}
