//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DynamicAppsEntities : DbContext
    {
        public DynamicAppsEntities()
            : base("name=DynamicAppsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMDynamicApplication> CMDynamicApplications { get; set; }
        public virtual DbSet<CMDynamicPackage> CMDynamicPackages { get; set; }
        public virtual DbSet<CMOperatingSystem> CMOperatingSystems { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DynamicAppCustomer> DynamicAppCustomers { get; set; }
    }
}
